- name: install php packages
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - php5
    - php5-fpm
    - php5-gd
    - php5-imagick
    - php5-mcrypt
    - php5-mysqlnd
    - php5-apcu
    - php5-curl
    - php5-memcached
    
- name: enable php5 mcrypt module
  shell: php5enmod mcrypt
  args:
    creates: /etc/php5/cli/conf.d/20-mcrypt.ini

- name: Install PHP Memcached extension (Debian).
  apt: name={{ item }} update_cache=yes state=latest
  with_items: 
    - memcached
  notify:
    - restart php5-fpm    
  